// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/jwt_verification_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/jwt_verification_usecase.go -destination=tests/mocks/mock_blacklist_checker.go -package=mocks -mock_names=BlacklistChecker=MockBlacklistChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBlacklistChecker is a mock of BlacklistChecker interface.
type MockBlacklistChecker struct {
	ctrl     *gomock.Controller
	recorder *MockBlacklistCheckerMockRecorder
	isgomock struct{}
}

// MockBlacklistCheckerMockRecorder is the mock recorder for MockBlacklistChecker.
type MockBlacklistCheckerMockRecorder struct {
	mock *MockBlacklistChecker
}

// NewMockBlacklistChecker creates a new mock instance.
func NewMockBlacklistChecker(ctrl *gomock.Controller) *MockBlacklistChecker {
	mock := &MockBlacklistChecker{ctrl: ctrl}
	mock.recorder = &MockBlacklistCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlacklistChecker) EXPECT() *MockBlacklistCheckerMockRecorder {
	return m.recorder
}

// IsBlacklisted mocks base method.
func (m *MockBlacklistChecker) IsBlacklisted(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlacklisted", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBlacklisted indicates an expected call of IsBlacklisted.
func (mr *MockBlacklistCheckerMockRecorder) IsBlacklisted(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlacklisted", reflect.TypeOf((*MockBlacklistChecker)(nil).IsBlacklisted), ctx, jti)
}
