// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/financial_account_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/financial_account_repository.go -destination=tests/mocks/mock_account_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/TubagusAldiMY/kasku/finance-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockFinancialAccountRepository is a mock of FinancialAccountRepository interface.
type MockFinancialAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFinancialAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockFinancialAccountRepositoryMockRecorder is the mock recorder for MockFinancialAccountRepository.
type MockFinancialAccountRepositoryMockRecorder struct {
	mock *MockFinancialAccountRepository
}

// NewMockFinancialAccountRepository creates a new mock instance.
func NewMockFinancialAccountRepository(ctrl *gomock.Controller) *MockFinancialAccountRepository {
	mock := &MockFinancialAccountRepository{ctrl: ctrl}
	mock.recorder = &MockFinancialAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinancialAccountRepository) EXPECT() *MockFinancialAccountRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockFinancialAccountRepository) CountByUserID(ctx context.Context, tenantSchema, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, tenantSchema, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockFinancialAccountRepositoryMockRecorder) CountByUserID(ctx, tenantSchema, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockFinancialAccountRepository)(nil).CountByUserID), ctx, tenantSchema, userID)
}

// Create mocks base method.
func (m *MockFinancialAccountRepository) Create(ctx context.Context, tenantSchema string, account *entity.FinancialAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tenantSchema, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFinancialAccountRepositoryMockRecorder) Create(ctx, tenantSchema, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFinancialAccountRepository)(nil).Create), ctx, tenantSchema, account)
}

// GetBalanceHistory mocks base method.
func (m *MockFinancialAccountRepository) GetBalanceHistory(ctx context.Context, tenantSchema, accountID string, limitMonths int) ([]entity.BalanceHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceHistory", ctx, tenantSchema, accountID, limitMonths)
	ret0, _ := ret[0].([]entity.BalanceHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceHistory indicates an expected call of GetBalanceHistory.
func (mr *MockFinancialAccountRepositoryMockRecorder) GetBalanceHistory(ctx, tenantSchema, accountID, limitMonths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceHistory", reflect.TypeOf((*MockFinancialAccountRepository)(nil).GetBalanceHistory), ctx, tenantSchema, accountID, limitMonths)
}

// GetByID mocks base method.
func (m *MockFinancialAccountRepository) GetByID(ctx context.Context, tenantSchema, id, userID string) (*entity.FinancialAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tenantSchema, id, userID)
	ret0, _ := ret[0].(*entity.FinancialAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFinancialAccountRepositoryMockRecorder) GetByID(ctx, tenantSchema, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFinancialAccountRepository)(nil).GetByID), ctx, tenantSchema, id, userID)
}

// List mocks base method.
func (m *MockFinancialAccountRepository) List(ctx context.Context, tenantSchema, userID string) ([]entity.FinancialAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantSchema, userID)
	ret0, _ := ret[0].([]entity.FinancialAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFinancialAccountRepositoryMockRecorder) List(ctx, tenantSchema, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFinancialAccountRepository)(nil).List), ctx, tenantSchema, userID)
}

// SoftDelete mocks base method.
func (m *MockFinancialAccountRepository) SoftDelete(ctx context.Context, tenantSchema, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, tenantSchema, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockFinancialAccountRepositoryMockRecorder) SoftDelete(ctx, tenantSchema, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockFinancialAccountRepository)(nil).SoftDelete), ctx, tenantSchema, id, userID)
}

// Update mocks base method.
func (m *MockFinancialAccountRepository) Update(ctx context.Context, tenantSchema string, account *entity.FinancialAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tenantSchema, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFinancialAccountRepositoryMockRecorder) Update(ctx, tenantSchema, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFinancialAccountRepository)(nil).Update), ctx, tenantSchema, account)
}
