// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/persistence/finance_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/infrastructure/persistence/finance_repository.go -destination=tests/mocks/mock_finance_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFinanceRepository is a mock of FinanceRepository interface.
type MockFinanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFinanceRepositoryMockRecorder
	isgomock struct{}
}

// MockFinanceRepositoryMockRecorder is the mock recorder for MockFinanceRepository.
type MockFinanceRepositoryMockRecorder struct {
	mock *MockFinanceRepository
}

// NewMockFinanceRepository creates a new mock instance.
func NewMockFinanceRepository(ctrl *gomock.Controller) *MockFinanceRepository {
	mock := &MockFinanceRepository{ctrl: ctrl}
	mock.recorder = &MockFinanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinanceRepository) EXPECT() *MockFinanceRepositoryMockRecorder {
	return m.recorder
}

// EnsureTenantRuntimeObjects mocks base method.
func (m *MockFinanceRepository) EnsureTenantRuntimeObjects(ctx context.Context, tenantSchema string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureTenantRuntimeObjects", ctx, tenantSchema)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureTenantRuntimeObjects indicates an expected call of EnsureTenantRuntimeObjects.
func (mr *MockFinanceRepositoryMockRecorder) EnsureTenantRuntimeObjects(ctx, tenantSchema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureTenantRuntimeObjects", reflect.TypeOf((*MockFinanceRepository)(nil).EnsureTenantRuntimeObjects), ctx, tenantSchema)
}

// ProvisionTenant mocks base method.
func (m *MockFinanceRepository) ProvisionTenant(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionTenant", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProvisionTenant indicates an expected call of ProvisionTenant.
func (mr *MockFinanceRepositoryMockRecorder) ProvisionTenant(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionTenant", reflect.TypeOf((*MockFinanceRepository)(nil).ProvisionTenant), ctx, userID)
}

// RemoveDefaultCategorySeeds mocks base method.
func (m *MockFinanceRepository) RemoveDefaultCategorySeeds(ctx context.Context, tenantSchema string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDefaultCategorySeeds", ctx, tenantSchema)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDefaultCategorySeeds indicates an expected call of RemoveDefaultCategorySeeds.
func (mr *MockFinanceRepositoryMockRecorder) RemoveDefaultCategorySeeds(ctx, tenantSchema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDefaultCategorySeeds", reflect.TypeOf((*MockFinanceRepository)(nil).RemoveDefaultCategorySeeds), ctx, tenantSchema)
}
