// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/persistence/user_profile_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/infrastructure/persistence/user_profile_repository.go -destination=tests/mocks/mock_user_profile_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	persistence "github.com/TubagusAldiMY/kasku/user-service/internal/infrastructure/persistence"
	gomock "go.uber.org/mock/gomock"
)

// MockUserProfileRepository is a mock of UserProfileRepository interface.
type MockUserProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockUserProfileRepositoryMockRecorder is the mock recorder for MockUserProfileRepository.
type MockUserProfileRepositoryMockRecorder struct {
	mock *MockUserProfileRepository
}

// NewMockUserProfileRepository creates a new mock instance.
func NewMockUserProfileRepository(ctrl *gomock.Controller) *MockUserProfileRepository {
	mock := &MockUserProfileRepository{ctrl: ctrl}
	mock.recorder = &MockUserProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileRepository) EXPECT() *MockUserProfileRepositoryMockRecorder {
	return m.recorder
}

// EnsureUserProfile mocks base method.
func (m *MockUserProfileRepository) EnsureUserProfile(ctx context.Context, userID, email, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureUserProfile", ctx, userID, email, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureUserProfile indicates an expected call of EnsureUserProfile.
func (mr *MockUserProfileRepositoryMockRecorder) EnsureUserProfile(ctx, userID, email, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureUserProfile", reflect.TypeOf((*MockUserProfileRepository)(nil).EnsureUserProfile), ctx, userID, email, username)
}

// GetUserProfile mocks base method.
func (m *MockUserProfileRepository) GetUserProfile(ctx context.Context, userID string) (*persistence.UserProfileRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", ctx, userID)
	ret0, _ := ret[0].(*persistence.UserProfileRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockUserProfileRepositoryMockRecorder) GetUserProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockUserProfileRepository)(nil).GetUserProfile), ctx, userID)
}

// UpdateUserProfile mocks base method.
func (m *MockUserProfileRepository) UpdateUserProfile(ctx context.Context, userID, username, displayName string) (*persistence.UserProfileRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, userID, username, displayName)
	ret0, _ := ret[0].(*persistence.UserProfileRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockUserProfileRepositoryMockRecorder) UpdateUserProfile(ctx, userID, username, displayName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockUserProfileRepository)(nil).UpdateUserProfile), ctx, userID, username, displayName)
}
