// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/persistence/billing_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/infrastructure/persistence/billing_repository.go -destination=tests/mocks/mock_subscription_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// CreateFreeSubscription mocks base method.
func (m *MockSubscriptionRepository) CreateFreeSubscription(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFreeSubscription", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFreeSubscription indicates an expected call of CreateFreeSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) CreateFreeSubscription(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFreeSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).CreateFreeSubscription), ctx, userID)
}
