// Code generated by MockGen. DO NOT EDIT.
// Source: get_tier_limits_usecase.go
//
// Generated by this command:
//
//	mockgen -source=get_tier_limits_usecase.go -destination=../../tests/mocks/mock_get_tier_limits_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/TubagusAldiMY/kasku/billing-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockGetTierLimitsUseCase is a mock of GetTierLimitsUseCase interface.
type MockGetTierLimitsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTierLimitsUseCaseMockRecorder
	isgomock struct{}
}

// MockGetTierLimitsUseCaseMockRecorder is the mock recorder for MockGetTierLimitsUseCase.
type MockGetTierLimitsUseCaseMockRecorder struct {
	mock *MockGetTierLimitsUseCase
}

// NewMockGetTierLimitsUseCase creates a new mock instance.
func NewMockGetTierLimitsUseCase(ctrl *gomock.Controller) *MockGetTierLimitsUseCase {
	mock := &MockGetTierLimitsUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTierLimitsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTierLimitsUseCase) EXPECT() *MockGetTierLimitsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetTierLimitsUseCase) Execute(ctx context.Context, userID string) (*entity.PlanLimits, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID)
	ret0, _ := ret[0].(*entity.PlanLimits)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetTierLimitsUseCaseMockRecorder) Execute(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetTierLimitsUseCase)(nil).Execute), ctx, userID)
}
