// Code generated by MockGen. DO NOT EDIT.
// Source: expire_subscriptions_usecase.go
//
// Generated by this command:
//
//	mockgen -source=expire_subscriptions_usecase.go -destination=../../tests/mocks/mock_expire_subscriptions_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExpireSubscriptionsUseCase is a mock of ExpireSubscriptionsUseCase interface.
type MockExpireSubscriptionsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockExpireSubscriptionsUseCaseMockRecorder
	isgomock struct{}
}

// MockExpireSubscriptionsUseCaseMockRecorder is the mock recorder for MockExpireSubscriptionsUseCase.
type MockExpireSubscriptionsUseCaseMockRecorder struct {
	mock *MockExpireSubscriptionsUseCase
}

// NewMockExpireSubscriptionsUseCase creates a new mock instance.
func NewMockExpireSubscriptionsUseCase(ctrl *gomock.Controller) *MockExpireSubscriptionsUseCase {
	mock := &MockExpireSubscriptionsUseCase{ctrl: ctrl}
	mock.recorder = &MockExpireSubscriptionsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpireSubscriptionsUseCase) EXPECT() *MockExpireSubscriptionsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExpireSubscriptionsUseCase) Execute(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockExpireSubscriptionsUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExpireSubscriptionsUseCase)(nil).Execute), ctx)
}
