// Code generated by MockGen. DO NOT EDIT.
// Source: list_plans_usecase.go
//
// Generated by this command:
//
//	mockgen -source=list_plans_usecase.go -destination=../../tests/mocks/mock_list_plans_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/TubagusAldiMY/kasku/billing-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockListPlansUseCase is a mock of ListPlansUseCase interface.
type MockListPlansUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListPlansUseCaseMockRecorder
	isgomock struct{}
}

// MockListPlansUseCaseMockRecorder is the mock recorder for MockListPlansUseCase.
type MockListPlansUseCaseMockRecorder struct {
	mock *MockListPlansUseCase
}

// NewMockListPlansUseCase creates a new mock instance.
func NewMockListPlansUseCase(ctrl *gomock.Controller) *MockListPlansUseCase {
	mock := &MockListPlansUseCase{ctrl: ctrl}
	mock.recorder = &MockListPlansUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListPlansUseCase) EXPECT() *MockListPlansUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListPlansUseCase) Execute(ctx context.Context) ([]entity.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].([]entity.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListPlansUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListPlansUseCase)(nil).Execute), ctx)
}
