// Code generated by MockGen. DO NOT EDIT.
// Source: get_subscription_usecase.go
//
// Generated by this command:
//
//	mockgen -source=get_subscription_usecase.go -destination=../../tests/mocks/mock_get_subscription_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/TubagusAldiMY/kasku/billing-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockGetSubscriptionUseCase is a mock of GetSubscriptionUseCase interface.
type MockGetSubscriptionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetSubscriptionUseCaseMockRecorder
	isgomock struct{}
}

// MockGetSubscriptionUseCaseMockRecorder is the mock recorder for MockGetSubscriptionUseCase.
type MockGetSubscriptionUseCaseMockRecorder struct {
	mock *MockGetSubscriptionUseCase
}

// NewMockGetSubscriptionUseCase creates a new mock instance.
func NewMockGetSubscriptionUseCase(ctrl *gomock.Controller) *MockGetSubscriptionUseCase {
	mock := &MockGetSubscriptionUseCase{ctrl: ctrl}
	mock.recorder = &MockGetSubscriptionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSubscriptionUseCase) EXPECT() *MockGetSubscriptionUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetSubscriptionUseCase) Execute(ctx context.Context, userID string) (*entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID)
	ret0, _ := ret[0].(*entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetSubscriptionUseCaseMockRecorder) Execute(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetSubscriptionUseCase)(nil).Execute), ctx, userID)
}
