// Code generated by MockGen. DO NOT EDIT.
// Source: subscription_repository.go
//
// Generated by this command:
//
//	mockgen -source=subscription_repository.go -destination=../../../tests/mocks/mock_subscription_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/TubagusAldiMY/kasku/billing-service/internal/domain/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// ActivateSubscription mocks base method.
func (m *MockSubscriptionRepository) ActivateSubscription(ctx context.Context, subscriptionID uuid.UUID, periodEnd time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateSubscription", ctx, subscriptionID, periodEnd)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateSubscription indicates an expected call of ActivateSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) ActivateSubscription(ctx, subscriptionID, periodEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).ActivateSubscription), ctx, subscriptionID, periodEnd)
}

// CreateSubscription mocks base method.
func (m *MockSubscriptionRepository) CreateSubscription(ctx context.Context, userID, planID uuid.UUID) (*entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, userID, planID)
	ret0, _ := ret[0].(*entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) CreateSubscription(ctx, userID, planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).CreateSubscription), ctx, userID, planID)
}

// ExpireSubscriptionAtomic mocks base method.
func (m *MockSubscriptionRepository) ExpireSubscriptionAtomic(ctx context.Context, subscriptionID, eventType, routingKey string, payload []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireSubscriptionAtomic", ctx, subscriptionID, eventType, routingKey, payload)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpireSubscriptionAtomic indicates an expected call of ExpireSubscriptionAtomic.
func (mr *MockSubscriptionRepositoryMockRecorder) ExpireSubscriptionAtomic(ctx, subscriptionID, eventType, routingKey, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireSubscriptionAtomic", reflect.TypeOf((*MockSubscriptionRepository)(nil).ExpireSubscriptionAtomic), ctx, subscriptionID, eventType, routingKey, payload)
}

// GetByUserID mocks base method.
func (m *MockSubscriptionRepository) GetByUserID(ctx context.Context, userID string) (*entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockSubscriptionRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetByUserID), ctx, userID)
}

// GetPlanWithLimits mocks base method.
func (m *MockSubscriptionRepository) GetPlanWithLimits(ctx context.Context, planID string) (*entity.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanWithLimits", ctx, planID)
	ret0, _ := ret[0].(*entity.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanWithLimits indicates an expected call of GetPlanWithLimits.
func (mr *MockSubscriptionRepositoryMockRecorder) GetPlanWithLimits(ctx, planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanWithLimits", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetPlanWithLimits), ctx, planID)
}

// InsertOutboxEvent mocks base method.
func (m *MockSubscriptionRepository) InsertOutboxEvent(ctx context.Context, eventType, routingKey string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOutboxEvent", ctx, eventType, routingKey, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOutboxEvent indicates an expected call of InsertOutboxEvent.
func (mr *MockSubscriptionRepositoryMockRecorder) InsertOutboxEvent(ctx, eventType, routingKey, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOutboxEvent", reflect.TypeOf((*MockSubscriptionRepository)(nil).InsertOutboxEvent), ctx, eventType, routingKey, payload)
}

// ListAllPlans mocks base method.
func (m *MockSubscriptionRepository) ListAllPlans(ctx context.Context) ([]entity.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPlans", ctx)
	ret0, _ := ret[0].([]entity.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPlans indicates an expected call of ListAllPlans.
func (mr *MockSubscriptionRepositoryMockRecorder) ListAllPlans(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPlans", reflect.TypeOf((*MockSubscriptionRepository)(nil).ListAllPlans), ctx)
}

// ListExpiredSubscriptions mocks base method.
func (m *MockSubscriptionRepository) ListExpiredSubscriptions(ctx context.Context) ([]entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredSubscriptions", ctx)
	ret0, _ := ret[0].([]entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredSubscriptions indicates an expected call of ListExpiredSubscriptions.
func (mr *MockSubscriptionRepositoryMockRecorder) ListExpiredSubscriptions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredSubscriptions", reflect.TypeOf((*MockSubscriptionRepository)(nil).ListExpiredSubscriptions), ctx)
}

// UpgradeSubscription mocks base method.
func (m *MockSubscriptionRepository) UpgradeSubscription(ctx context.Context, subscriptionID, newPlanID uuid.UUID, periodEnd time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpgradeSubscription", ctx, subscriptionID, newPlanID, periodEnd)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpgradeSubscription indicates an expected call of UpgradeSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) UpgradeSubscription(ctx, subscriptionID, newPlanID, periodEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).UpgradeSubscription), ctx, subscriptionID, newPlanID, periodEnd)
}

// UpdateStatus mocks base method.
func (m *MockSubscriptionRepository) UpdateStatus(ctx context.Context, subscriptionID string, status entity.SubscriptionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, subscriptionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockSubscriptionRepositoryMockRecorder) UpdateStatus(ctx, subscriptionID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockSubscriptionRepository)(nil).UpdateStatus), ctx, subscriptionID, status)
}
