// Code generated by MockGen. DO NOT EDIT.
// Source: rabbitmq_publisher.go
//
// Generated by this command:
//
//	mockgen -source=rabbitmq_publisher.go -destination=../../../tests/mocks/mock_event_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	messaging "github.com/TubagusAldiMY/kasku/billing-service/internal/infrastructure/messaging"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventPublisher)(nil).Close))
}

// Ping mocks base method.
func (m *MockEventPublisher) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockEventPublisherMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockEventPublisher)(nil).Ping))
}

// PublishRaw mocks base method.
func (m *MockEventPublisher) PublishRaw(ctx context.Context, routingKey string, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRaw", ctx, routingKey, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRaw indicates an expected call of PublishRaw.
func (mr *MockEventPublisherMockRecorder) PublishRaw(ctx, routingKey, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRaw", reflect.TypeOf((*MockEventPublisher)(nil).PublishRaw), ctx, routingKey, body)
}

// PublishSubscriptionExpired mocks base method.
func (m *MockEventPublisher) PublishSubscriptionExpired(ctx context.Context, event messaging.SubscriptionExpiredEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSubscriptionExpired", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSubscriptionExpired indicates an expected call of PublishSubscriptionExpired.
func (mr *MockEventPublisherMockRecorder) PublishSubscriptionExpired(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSubscriptionExpired", reflect.TypeOf((*MockEventPublisher)(nil).PublishSubscriptionExpired), ctx, event)
}

// PublishSubscriptionExpiring mocks base method.
func (m *MockEventPublisher) PublishSubscriptionExpiring(ctx context.Context, event messaging.SubscriptionExpiringEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSubscriptionExpiring", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSubscriptionExpiring indicates an expected call of PublishSubscriptionExpiring.
func (mr *MockEventPublisherMockRecorder) PublishSubscriptionExpiring(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSubscriptionExpiring", reflect.TypeOf((*MockEventPublisher)(nil).PublishSubscriptionExpiring), ctx, event)
}
