// Code generated by MockGen. DO NOT EDIT.
// Source: register_usecase.go
//
// Generated by this command:
//
//	mockgen -source=register_usecase.go -destination=../../tests/mocks/mock_register_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/TubagusAldiMY/kasku/auth-service/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockRegisterUseCase is a mock of RegisterUseCase interface.
type MockRegisterUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterUseCaseMockRecorder
	isgomock struct{}
}

// MockRegisterUseCaseMockRecorder is the mock recorder for MockRegisterUseCase.
type MockRegisterUseCaseMockRecorder struct {
	mock *MockRegisterUseCase
}

// NewMockRegisterUseCase creates a new mock instance.
func NewMockRegisterUseCase(ctrl *gomock.Controller) *MockRegisterUseCase {
	mock := &MockRegisterUseCase{ctrl: ctrl}
	mock.recorder = &MockRegisterUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegisterUseCase) EXPECT() *MockRegisterUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRegisterUseCase) Execute(ctx context.Context, input usecase.RegisterInput) (*usecase.RegisterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.RegisterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRegisterUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRegisterUseCase)(nil).Execute), ctx, input)
}
