// Code generated by MockGen. DO NOT EDIT.
// Source: refresh_token_usecase.go
//
// Generated by this command:
//
//	mockgen -source=refresh_token_usecase.go -destination=../../tests/mocks/mock_refresh_token_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/TubagusAldiMY/kasku/auth-service/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenUseCase is a mock of RefreshTokenUseCase interface.
type MockRefreshTokenUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenUseCaseMockRecorder
	isgomock struct{}
}

// MockRefreshTokenUseCaseMockRecorder is the mock recorder for MockRefreshTokenUseCase.
type MockRefreshTokenUseCaseMockRecorder struct {
	mock *MockRefreshTokenUseCase
}

// NewMockRefreshTokenUseCase creates a new mock instance.
func NewMockRefreshTokenUseCase(ctrl *gomock.Controller) *MockRefreshTokenUseCase {
	mock := &MockRefreshTokenUseCase{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenUseCase) EXPECT() *MockRefreshTokenUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRefreshTokenUseCase) Execute(ctx context.Context, input usecase.RefreshInput) (*usecase.LoginOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*usecase.LoginOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRefreshTokenUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRefreshTokenUseCase)(nil).Execute), ctx, input)
}
