// Code generated by MockGen. DO NOT EDIT.
// Source: change_password_usecase.go
//
// Generated by this command:
//
//	mockgen -source=change_password_usecase.go -destination=../../tests/mocks/mock_change_password_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockChangePasswordUseCase is a mock of ChangePasswordUseCase interface.
type MockChangePasswordUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockChangePasswordUseCaseMockRecorder
	isgomock struct{}
}

// MockChangePasswordUseCaseMockRecorder is the mock recorder for MockChangePasswordUseCase.
type MockChangePasswordUseCaseMockRecorder struct {
	mock *MockChangePasswordUseCase
}

// NewMockChangePasswordUseCase creates a new mock instance.
func NewMockChangePasswordUseCase(ctrl *gomock.Controller) *MockChangePasswordUseCase {
	mock := &MockChangePasswordUseCase{ctrl: ctrl}
	mock.recorder = &MockChangePasswordUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangePasswordUseCase) EXPECT() *MockChangePasswordUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockChangePasswordUseCase) Execute(ctx context.Context, userID uuid.UUID, currentPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, userID, currentPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockChangePasswordUseCaseMockRecorder) Execute(ctx, userID, currentPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockChangePasswordUseCase)(nil).Execute), ctx, userID, currentPassword, newPassword)
}
