// Code generated by MockGen. DO NOT EDIT.
// Source: resend_verification_usecase.go
//
// Generated by this command:
//
//	mockgen -source=resend_verification_usecase.go -destination=../../tests/mocks/mock_resend_verification_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResendVerificationUseCase is a mock of ResendVerificationUseCase interface.
type MockResendVerificationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockResendVerificationUseCaseMockRecorder
	isgomock struct{}
}

// MockResendVerificationUseCaseMockRecorder is the mock recorder for MockResendVerificationUseCase.
type MockResendVerificationUseCaseMockRecorder struct {
	mock *MockResendVerificationUseCase
}

// NewMockResendVerificationUseCase creates a new mock instance.
func NewMockResendVerificationUseCase(ctrl *gomock.Controller) *MockResendVerificationUseCase {
	mock := &MockResendVerificationUseCase{ctrl: ctrl}
	mock.recorder = &MockResendVerificationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResendVerificationUseCase) EXPECT() *MockResendVerificationUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockResendVerificationUseCase) Execute(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockResendVerificationUseCaseMockRecorder) Execute(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockResendVerificationUseCase)(nil).Execute), ctx, email)
}
