// Code generated by MockGen. DO NOT EDIT.
// Source: email_verification_repository.go
//
// Generated by this command:
//
//	mockgen -source=email_verification_repository.go -destination=../../../tests/mocks/mock_email_verification_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/TubagusAldiMY/kasku/auth-service/internal/domain/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailVerificationRepository is a mock of EmailVerificationRepository interface.
type MockEmailVerificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailVerificationRepositoryMockRecorder is the mock recorder for MockEmailVerificationRepository.
type MockEmailVerificationRepositoryMockRecorder struct {
	mock *MockEmailVerificationRepository
}

// NewMockEmailVerificationRepository creates a new mock instance.
func NewMockEmailVerificationRepository(ctrl *gomock.Controller) *MockEmailVerificationRepository {
	mock := &MockEmailVerificationRepository{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationRepository) EXPECT() *MockEmailVerificationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmailVerificationRepository) Create(ctx context.Context, verification *entity.EmailVerification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, verification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmailVerificationRepositoryMockRecorder) Create(ctx, verification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailVerificationRepository)(nil).Create), ctx, verification)
}

// FindActiveByTokenHash mocks base method.
func (m *MockEmailVerificationRepository) FindActiveByTokenHash(ctx context.Context, tokenHash string) (*entity.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*entity.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByTokenHash indicates an expected call of FindActiveByTokenHash.
func (mr *MockEmailVerificationRepositoryMockRecorder) FindActiveByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByTokenHash", reflect.TypeOf((*MockEmailVerificationRepository)(nil).FindActiveByTokenHash), ctx, tokenHash)
}

// InvalidateAllActiveByUserID mocks base method.
func (m *MockEmailVerificationRepository) InvalidateAllActiveByUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAllActiveByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAllActiveByUserID indicates an expected call of InvalidateAllActiveByUserID.
func (mr *MockEmailVerificationRepositoryMockRecorder) InvalidateAllActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAllActiveByUserID", reflect.TypeOf((*MockEmailVerificationRepository)(nil).InvalidateAllActiveByUserID), ctx, userID)
}

// MarkAsVerified mocks base method.
func (m *MockEmailVerificationRepository) MarkAsVerified(ctx context.Context, verificationID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsVerified", ctx, verificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsVerified indicates an expected call of MarkAsVerified.
func (mr *MockEmailVerificationRepositoryMockRecorder) MarkAsVerified(ctx, verificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsVerified", reflect.TypeOf((*MockEmailVerificationRepository)(nil).MarkAsVerified), ctx, verificationID)
}
