// Code generated by MockGen. DO NOT EDIT.
// Source: rabbitmq_publisher.go
//
// Generated by this command:
//
//	mockgen -source=rabbitmq_publisher.go -destination=../../../tests/mocks/mock_event_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	messaging "github.com/TubagusAldiMY/kasku/auth-service/internal/infrastructure/messaging"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventPublisher)(nil).Close))
}

// Ping mocks base method.
func (m *MockEventPublisher) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockEventPublisherMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockEventPublisher)(nil).Ping))
}

// PublishEmailVerificationResent mocks base method.
func (m *MockEventPublisher) PublishEmailVerificationResent(ctx context.Context, event messaging.EmailVerificationResentEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEmailVerificationResent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishEmailVerificationResent indicates an expected call of PublishEmailVerificationResent.
func (mr *MockEventPublisherMockRecorder) PublishEmailVerificationResent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEmailVerificationResent", reflect.TypeOf((*MockEventPublisher)(nil).PublishEmailVerificationResent), ctx, event)
}

// PublishPasswordResetRequested mocks base method.
func (m *MockEventPublisher) PublishPasswordResetRequested(ctx context.Context, event messaging.PasswordResetRequestedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPasswordResetRequested", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPasswordResetRequested indicates an expected call of PublishPasswordResetRequested.
func (mr *MockEventPublisherMockRecorder) PublishPasswordResetRequested(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPasswordResetRequested", reflect.TypeOf((*MockEventPublisher)(nil).PublishPasswordResetRequested), ctx, event)
}

// PublishUserRegistered mocks base method.
func (m *MockEventPublisher) PublishUserRegistered(ctx context.Context, event messaging.UserRegisteredEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUserRegistered", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUserRegistered indicates an expected call of PublishUserRegistered.
func (mr *MockEventPublisherMockRecorder) PublishUserRegistered(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUserRegistered", reflect.TypeOf((*MockEventPublisher)(nil).PublishUserRegistered), ctx, event)
}
