// Code generated by MockGen. DO NOT EDIT.
// Source: password_reset_repository.go
//
// Generated by this command:
//
//	mockgen -source=password_reset_repository.go -destination=../../../tests/mocks/mock_password_reset_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/TubagusAldiMY/kasku/auth-service/internal/domain/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordResetRepository is a mock of PasswordResetRepository interface.
type MockPasswordResetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordResetRepositoryMockRecorder is the mock recorder for MockPasswordResetRepository.
type MockPasswordResetRepositoryMockRecorder struct {
	mock *MockPasswordResetRepository
}

// NewMockPasswordResetRepository creates a new mock instance.
func NewMockPasswordResetRepository(ctrl *gomock.Controller) *MockPasswordResetRepository {
	mock := &MockPasswordResetRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordResetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetRepository) EXPECT() *MockPasswordResetRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasswordResetRepository) Create(ctx context.Context, token *entity.PasswordResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasswordResetRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordResetRepository)(nil).Create), ctx, token)
}

// FindActiveByTokenHash mocks base method.
func (m *MockPasswordResetRepository) FindActiveByTokenHash(ctx context.Context, tokenHash string) (*entity.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*entity.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByTokenHash indicates an expected call of FindActiveByTokenHash.
func (mr *MockPasswordResetRepositoryMockRecorder) FindActiveByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByTokenHash", reflect.TypeOf((*MockPasswordResetRepository)(nil).FindActiveByTokenHash), ctx, tokenHash)
}

// MarkAsUsed mocks base method.
func (m *MockPasswordResetRepository) MarkAsUsed(ctx context.Context, tokenID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsUsed", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsUsed indicates an expected call of MarkAsUsed.
func (mr *MockPasswordResetRepositoryMockRecorder) MarkAsUsed(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsUsed", reflect.TypeOf((*MockPasswordResetRepository)(nil).MarkAsUsed), ctx, tokenID)
}

// MockTransactionalResetPasswordRepository is a mock of TransactionalResetPasswordRepository interface.
type MockTransactionalResetPasswordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionalResetPasswordRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionalResetPasswordRepositoryMockRecorder is the mock recorder for MockTransactionalResetPasswordRepository.
type MockTransactionalResetPasswordRepositoryMockRecorder struct {
	mock *MockTransactionalResetPasswordRepository
}

// NewMockTransactionalResetPasswordRepository creates a new mock instance.
func NewMockTransactionalResetPasswordRepository(ctrl *gomock.Controller) *MockTransactionalResetPasswordRepository {
	mock := &MockTransactionalResetPasswordRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionalResetPasswordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionalResetPasswordRepository) EXPECT() *MockTransactionalResetPasswordRepositoryMockRecorder {
	return m.recorder
}

// ExecuteResetPasswordTx mocks base method.
func (m *MockTransactionalResetPasswordRepository) ExecuteResetPasswordTx(ctx context.Context, userID uuid.UUID, newPasswordHash string, tokenID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteResetPasswordTx", ctx, userID, newPasswordHash, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteResetPasswordTx indicates an expected call of ExecuteResetPasswordTx.
func (mr *MockTransactionalResetPasswordRepositoryMockRecorder) ExecuteResetPasswordTx(ctx, userID, newPasswordHash, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteResetPasswordTx", reflect.TypeOf((*MockTransactionalResetPasswordRepository)(nil).ExecuteResetPasswordTx), ctx, userID, newPasswordHash, tokenID)
}
