// Code generated by MockGen. DO NOT EDIT.
// Source: validate_token_usecase.go
//
// Generated by this command:
//
//	mockgen -source=validate_token_usecase.go -destination=../../tests/mocks/mock_validate_token_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/TubagusAldiMY/kasku/auth-service/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenBlacklistChecker is a mock of TokenBlacklistChecker interface.
type MockTokenBlacklistChecker struct {
	ctrl     *gomock.Controller
	recorder *MockTokenBlacklistCheckerMockRecorder
	isgomock struct{}
}

// MockTokenBlacklistCheckerMockRecorder is the mock recorder for MockTokenBlacklistChecker.
type MockTokenBlacklistCheckerMockRecorder struct {
	mock *MockTokenBlacklistChecker
}

// NewMockTokenBlacklistChecker creates a new mock instance.
func NewMockTokenBlacklistChecker(ctrl *gomock.Controller) *MockTokenBlacklistChecker {
	mock := &MockTokenBlacklistChecker{ctrl: ctrl}
	mock.recorder = &MockTokenBlacklistCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenBlacklistChecker) EXPECT() *MockTokenBlacklistCheckerMockRecorder {
	return m.recorder
}

// IsJTIBlacklisted mocks base method.
func (m *MockTokenBlacklistChecker) IsJTIBlacklisted(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsJTIBlacklisted", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsJTIBlacklisted indicates an expected call of IsJTIBlacklisted.
func (mr *MockTokenBlacklistCheckerMockRecorder) IsJTIBlacklisted(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsJTIBlacklisted", reflect.TypeOf((*MockTokenBlacklistChecker)(nil).IsJTIBlacklisted), ctx, jti)
}

// MockValidateAccessTokenUseCase is a mock of ValidateAccessTokenUseCase interface.
type MockValidateAccessTokenUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockValidateAccessTokenUseCaseMockRecorder
	isgomock struct{}
}

// MockValidateAccessTokenUseCaseMockRecorder is the mock recorder for MockValidateAccessTokenUseCase.
type MockValidateAccessTokenUseCaseMockRecorder struct {
	mock *MockValidateAccessTokenUseCase
}

// NewMockValidateAccessTokenUseCase creates a new mock instance.
func NewMockValidateAccessTokenUseCase(ctrl *gomock.Controller) *MockValidateAccessTokenUseCase {
	mock := &MockValidateAccessTokenUseCase{ctrl: ctrl}
	mock.recorder = &MockValidateAccessTokenUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidateAccessTokenUseCase) EXPECT() *MockValidateAccessTokenUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockValidateAccessTokenUseCase) Execute(ctx context.Context, tokenString string) (*usecase.JWTClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, tokenString)
	ret0, _ := ret[0].(*usecase.JWTClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockValidateAccessTokenUseCaseMockRecorder) Execute(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockValidateAccessTokenUseCase)(nil).Execute), ctx, tokenString)
}
