// Code generated by MockGen. DO NOT EDIT.
// Source: forgot_password_usecase.go
//
// Generated by this command:
//
//	mockgen -source=forgot_password_usecase.go -destination=../../tests/mocks/mock_forgot_password_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockForgotPasswordUseCase is a mock of ForgotPasswordUseCase interface.
type MockForgotPasswordUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockForgotPasswordUseCaseMockRecorder
	isgomock struct{}
}

// MockForgotPasswordUseCaseMockRecorder is the mock recorder for MockForgotPasswordUseCase.
type MockForgotPasswordUseCaseMockRecorder struct {
	mock *MockForgotPasswordUseCase
}

// NewMockForgotPasswordUseCase creates a new mock instance.
func NewMockForgotPasswordUseCase(ctrl *gomock.Controller) *MockForgotPasswordUseCase {
	mock := &MockForgotPasswordUseCase{ctrl: ctrl}
	mock.recorder = &MockForgotPasswordUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForgotPasswordUseCase) EXPECT() *MockForgotPasswordUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockForgotPasswordUseCase) Execute(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockForgotPasswordUseCaseMockRecorder) Execute(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockForgotPasswordUseCase)(nil).Execute), ctx, email)
}
