// Code generated by MockGen. DO NOT EDIT.
// Source: reset_password_usecase.go
//
// Generated by this command:
//
//	mockgen -source=reset_password_usecase.go -destination=../../tests/mocks/mock_reset_password_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResetPasswordUseCase is a mock of ResetPasswordUseCase interface.
type MockResetPasswordUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockResetPasswordUseCaseMockRecorder
	isgomock struct{}
}

// MockResetPasswordUseCaseMockRecorder is the mock recorder for MockResetPasswordUseCase.
type MockResetPasswordUseCaseMockRecorder struct {
	mock *MockResetPasswordUseCase
}

// NewMockResetPasswordUseCase creates a new mock instance.
func NewMockResetPasswordUseCase(ctrl *gomock.Controller) *MockResetPasswordUseCase {
	mock := &MockResetPasswordUseCase{ctrl: ctrl}
	mock.recorder = &MockResetPasswordUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetPasswordUseCase) EXPECT() *MockResetPasswordUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockResetPasswordUseCase) Execute(ctx context.Context, rawToken, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, rawToken, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockResetPasswordUseCaseMockRecorder) Execute(ctx, rawToken, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockResetPasswordUseCase)(nil).Execute), ctx, rawToken, newPassword)
}
