// Code generated by MockGen. DO NOT EDIT.
// Source: logout_usecase.go
//
// Generated by this command:
//
//	mockgen -source=logout_usecase.go -destination=../../tests/mocks/mock_logout_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	usecase "github.com/TubagusAldiMY/kasku/auth-service/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenBlacklister is a mock of TokenBlacklister interface.
type MockTokenBlacklister struct {
	ctrl     *gomock.Controller
	recorder *MockTokenBlacklisterMockRecorder
	isgomock struct{}
}

// MockTokenBlacklisterMockRecorder is the mock recorder for MockTokenBlacklister.
type MockTokenBlacklisterMockRecorder struct {
	mock *MockTokenBlacklister
}

// NewMockTokenBlacklister creates a new mock instance.
func NewMockTokenBlacklister(ctrl *gomock.Controller) *MockTokenBlacklister {
	mock := &MockTokenBlacklister{ctrl: ctrl}
	mock.recorder = &MockTokenBlacklisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenBlacklister) EXPECT() *MockTokenBlacklisterMockRecorder {
	return m.recorder
}

// BlacklistJTI mocks base method.
func (m *MockTokenBlacklister) BlacklistJTI(ctx context.Context, jti string, remainingTTL time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlacklistJTI", ctx, jti, remainingTTL)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlacklistJTI indicates an expected call of BlacklistJTI.
func (mr *MockTokenBlacklisterMockRecorder) BlacklistJTI(ctx, jti, remainingTTL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlacklistJTI", reflect.TypeOf((*MockTokenBlacklister)(nil).BlacklistJTI), ctx, jti, remainingTTL)
}

// MockLogoutUseCase is a mock of LogoutUseCase interface.
type MockLogoutUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLogoutUseCaseMockRecorder
	isgomock struct{}
}

// MockLogoutUseCaseMockRecorder is the mock recorder for MockLogoutUseCase.
type MockLogoutUseCaseMockRecorder struct {
	mock *MockLogoutUseCase
}

// NewMockLogoutUseCase creates a new mock instance.
func NewMockLogoutUseCase(ctrl *gomock.Controller) *MockLogoutUseCase {
	mock := &MockLogoutUseCase{ctrl: ctrl}
	mock.recorder = &MockLogoutUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogoutUseCase) EXPECT() *MockLogoutUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLogoutUseCase) Execute(ctx context.Context, input usecase.LogoutInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockLogoutUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLogoutUseCase)(nil).Execute), ctx, input)
}
