// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/subscription_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/subscription_repository.go -destination=tests/mocks/mock_subscription_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/TubagusAldiMY/kasku/admin-service/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// FindPlanByName mocks base method.
func (m *MockSubscriptionRepository) FindPlanByName(ctx context.Context, name string) (uuid.UUID, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPlanByName", ctx, name)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPlanByName indicates an expected call of FindPlanByName.
func (mr *MockSubscriptionRepositoryMockRecorder) FindPlanByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPlanByName", reflect.TypeOf((*MockSubscriptionRepository)(nil).FindPlanByName), ctx, name)
}

// GetByUserID mocks base method.
func (m *MockSubscriptionRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*repository.SubscriptionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*repository.SubscriptionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockSubscriptionRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetByUserID), ctx, userID)
}

// GetByUserIDs mocks base method.
func (m *MockSubscriptionRepository) GetByUserIDs(ctx context.Context, userIDs []uuid.UUID) (map[uuid.UUID]repository.SubscriptionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[uuid.UUID]repository.SubscriptionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDs indicates an expected call of GetByUserIDs.
func (mr *MockSubscriptionRepositoryMockRecorder) GetByUserIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDs", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetByUserIDs), ctx, userIDs)
}

// UpdatePlan mocks base method.
func (m *MockSubscriptionRepository) UpdatePlan(ctx context.Context, subscriptionID, newPlanID uuid.UUID, periodStart time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlan", ctx, subscriptionID, newPlanID, periodStart)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlan indicates an expected call of UpdatePlan.
func (mr *MockSubscriptionRepositoryMockRecorder) UpdatePlan(ctx, subscriptionID, newPlanID, periodStart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlan", reflect.TypeOf((*MockSubscriptionRepository)(nil).UpdatePlan), ctx, subscriptionID, newPlanID, periodStart)
}
