// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/admin_user_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/admin_user_repository.go -destination=tests/mocks/mock_admin_user_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/TubagusAldiMY/kasku/admin-service/internal/domain/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminUserRepository is a mock of AdminUserRepository interface.
type MockAdminUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminUserRepositoryMockRecorder is the mock recorder for MockAdminUserRepository.
type MockAdminUserRepositoryMockRecorder struct {
	mock *MockAdminUserRepository
}

// NewMockAdminUserRepository creates a new mock instance.
func NewMockAdminUserRepository(ctrl *gomock.Controller) *MockAdminUserRepository {
	mock := &MockAdminUserRepository{ctrl: ctrl}
	mock.recorder = &MockAdminUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUserRepository) EXPECT() *MockAdminUserRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockAdminUserRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockAdminUserRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockAdminUserRepository)(nil).Count), ctx)
}

// CreateBootstrap mocks base method.
func (m *MockAdminUserRepository) CreateBootstrap(ctx context.Context, admin *entity.AdminUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBootstrap", ctx, admin)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBootstrap indicates an expected call of CreateBootstrap.
func (mr *MockAdminUserRepositoryMockRecorder) CreateBootstrap(ctx, admin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBootstrap", reflect.TypeOf((*MockAdminUserRepository)(nil).CreateBootstrap), ctx, admin)
}

// FindByID mocks base method.
func (m *MockAdminUserRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAdminUserRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAdminUserRepository)(nil).FindByID), ctx, id)
}

// FindByUsername mocks base method.
func (m *MockAdminUserRepository) FindByUsername(ctx context.Context, username string) (*entity.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsername", ctx, username)
	ret0, _ := ret[0].(*entity.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsername indicates an expected call of FindByUsername.
func (mr *MockAdminUserRepositoryMockRecorder) FindByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsername", reflect.TypeOf((*MockAdminUserRepository)(nil).FindByUsername), ctx, username)
}

// UpdateLastLogin mocks base method.
func (m *MockAdminUserRepository) UpdateLastLogin(ctx context.Context, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockAdminUserRepositoryMockRecorder) UpdateLastLogin(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockAdminUserRepository)(nil).UpdateLastLogin), ctx, id, at)
}
