// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/payment_read_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/payment_read_repository.go -destination=tests/mocks/mock_payment_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/TubagusAldiMY/kasku/admin-service/internal/domain/entity"
	repository "github.com/TubagusAldiMY/kasku/admin-service/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentReadRepository is a mock of PaymentReadRepository interface.
type MockPaymentReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentReadRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentReadRepositoryMockRecorder is the mock recorder for MockPaymentReadRepository.
type MockPaymentReadRepositoryMockRecorder struct {
	mock *MockPaymentReadRepository
}

// NewMockPaymentReadRepository creates a new mock instance.
func NewMockPaymentReadRepository(ctrl *gomock.Controller) *MockPaymentReadRepository {
	mock := &MockPaymentReadRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentReadRepository) EXPECT() *MockPaymentReadRepositoryMockRecorder {
	return m.recorder
}

// CountByTier mocks base method.
func (m *MockPaymentReadRepository) CountByTier(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTier", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTier indicates an expected call of CountByTier.
func (mr *MockPaymentReadRepositoryMockRecorder) CountByTier(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTier", reflect.TypeOf((*MockPaymentReadRepository)(nil).CountByTier), ctx)
}

// CountCancelledSince mocks base method.
func (m *MockPaymentReadRepository) CountCancelledSince(ctx context.Context, since time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCancelledSince", ctx, since)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCancelledSince indicates an expected call of CountCancelledSince.
func (mr *MockPaymentReadRepositoryMockRecorder) CountCancelledSince(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCancelledSince", reflect.TypeOf((*MockPaymentReadRepository)(nil).CountCancelledSince), ctx, since)
}

// CountMRRActive mocks base method.
func (m *MockPaymentReadRepository) CountMRRActive(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMRRActive", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMRRActive indicates an expected call of CountMRRActive.
func (mr *MockPaymentReadRepositoryMockRecorder) CountMRRActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMRRActive", reflect.TypeOf((*MockPaymentReadRepository)(nil).CountMRRActive), ctx)
}

// List mocks base method.
func (m *MockPaymentReadRepository) List(ctx context.Context, filter repository.PaymentListFilter) ([]entity.PaymentSummary, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]entity.PaymentSummary)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPaymentReadRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPaymentReadRepository)(nil).List), ctx, filter)
}
