// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/user_read_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/user_read_repository.go -destination=tests/mocks/mock_user_repositories.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/TubagusAldiMY/kasku/admin-service/internal/domain/entity"
	repository "github.com/TubagusAldiMY/kasku/admin-service/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserReadRepository is a mock of UserReadRepository interface.
type MockUserReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserReadRepositoryMockRecorder
	isgomock struct{}
}

// MockUserReadRepositoryMockRecorder is the mock recorder for MockUserReadRepository.
type MockUserReadRepositoryMockRecorder struct {
	mock *MockUserReadRepository
}

// NewMockUserReadRepository creates a new mock instance.
func NewMockUserReadRepository(ctrl *gomock.Controller) *MockUserReadRepository {
	mock := &MockUserReadRepository{ctrl: ctrl}
	mock.recorder = &MockUserReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserReadRepository) EXPECT() *MockUserReadRepositoryMockRecorder {
	return m.recorder
}

// CountActive mocks base method.
func (m *MockUserReadRepository) CountActive(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActive", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActive indicates an expected call of CountActive.
func (mr *MockUserReadRepositoryMockRecorder) CountActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActive", reflect.TypeOf((*MockUserReadRepository)(nil).CountActive), ctx)
}

// CountCreatedSince mocks base method.
func (m *MockUserReadRepository) CountCreatedSince(ctx context.Context, since time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCreatedSince", ctx, since)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCreatedSince indicates an expected call of CountCreatedSince.
func (mr *MockUserReadRepositoryMockRecorder) CountCreatedSince(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCreatedSince", reflect.TypeOf((*MockUserReadRepository)(nil).CountCreatedSince), ctx, since)
}

// CountTotal mocks base method.
func (m *MockUserReadRepository) CountTotal(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotal", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotal indicates an expected call of CountTotal.
func (mr *MockUserReadRepositoryMockRecorder) CountTotal(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotal", reflect.TypeOf((*MockUserReadRepository)(nil).CountTotal), ctx)
}

// GetByID mocks base method.
func (m *MockUserReadRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.UserSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.UserSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserReadRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserReadRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockUserReadRepository) List(ctx context.Context, filter repository.UserListFilter) ([]entity.UserSummary, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]entity.UserSummary)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserReadRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserReadRepository)(nil).List), ctx, filter)
}

// MockUserWriteRepository is a mock of UserWriteRepository interface.
type MockUserWriteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserWriteRepositoryMockRecorder
	isgomock struct{}
}

// MockUserWriteRepositoryMockRecorder is the mock recorder for MockUserWriteRepository.
type MockUserWriteRepositoryMockRecorder struct {
	mock *MockUserWriteRepository
}

// NewMockUserWriteRepository creates a new mock instance.
func NewMockUserWriteRepository(ctrl *gomock.Controller) *MockUserWriteRepository {
	mock := &MockUserWriteRepository{ctrl: ctrl}
	mock.recorder = &MockUserWriteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserWriteRepository) EXPECT() *MockUserWriteRepositoryMockRecorder {
	return m.recorder
}

// SetIsActive mocks base method.
func (m *MockUserWriteRepository) SetIsActive(ctx context.Context, userID uuid.UUID, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockUserWriteRepositoryMockRecorder) SetIsActive(ctx, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockUserWriteRepository)(nil).SetIsActive), ctx, userID, isActive)
}
